# Generated by Django 4.1.7 on 2023-03-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciphline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Category',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
